
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Tsuru release compilation
      run: |
        brew install cmake
        git submodule init
        git submodule update
        mkdir build
        cd build
        cmake ..
        cmake --build . -C Release
